USE [master]
GO

/****** Object:  Database [KimVetKlinika]    Script Date: 26.10.2021 12:45:49 ******/
CREATE DATABASE [KimVetKlinika]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KimVetKlinika', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\KimVetKlinika.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KimVetKlinika_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\KimVetKlinika_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KimVetKlinika].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KimVetKlinika] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KimVetKlinika] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KimVetKlinika] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KimVetKlinika] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KimVetKlinika] SET ARITHABORT OFF 
GO

ALTER DATABASE [KimVetKlinika] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KimVetKlinika] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KimVetKlinika] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KimVetKlinika] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KimVetKlinika] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KimVetKlinika] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KimVetKlinika] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KimVetKlinika] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KimVetKlinika] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KimVetKlinika] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KimVetKlinika] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KimVetKlinika] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KimVetKlinika] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KimVetKlinika] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KimVetKlinika] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KimVetKlinika] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KimVetKlinika] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KimVetKlinika] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KimVetKlinika] SET  MULTI_USER 
GO

ALTER DATABASE [KimVetKlinika] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KimVetKlinika] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KimVetKlinika] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KimVetKlinika] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KimVetKlinika] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KimVetKlinika] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [KimVetKlinika] SET QUERY_STORE = OFF
GO

ALTER DATABASE [KimVetKlinika] SET  READ_WRITE 
GO

